### ISSUE TITLE
Make Web Pages responsive

### ISSUE THREAD

**Issue by abhishak3** [the-iter8/Noted#1]
Currently, Web Pages are not responsive. Try to make them responsive so that it looks good on every screen size.

**Comment by abhishak3** [comment]
Also, your slice animation is working for the first task only. Also, fix that.

**Comment by abhishak3** [comment]
![image](https://user-images.githubusercontent.com/77143429/167068796-f548fa70-7c07-4ff4-a801-4da43aefced5.png)
Currently, not satisfied with the tablet or mobile layout.
Things to fix:
1. Align the buttons.
2. Add support for mobile phone layout.

Footer is working great and is responsive.
@the-iter8

**Comment by the-iter8** [comment]
Pushed new edits and made it better for smaller devices. Any feedback is greatly appreciated. And Will close the issue upon confirmation from all the contributors.

**Comment by the-iter8** [comment]
Done.

**Comment by abhishak3** [comment]
Please only close the issue when all the contributors gave your fix a green flag.

**Comment by abhishak3** [comment]
Nice Work anyways
