### ISSUE TITLE
Orientation changes content

### ISSUE THREAD

**Issue by abhishak3** [the-iter8/Noted#11]
While on portrait mode, our website shows that we have curated a new app for them on the play store app. But as soon as we change the orientation to landscape our app is working again. I think this needs to be fixed.

**Comment by the-iter8** [comment]
While on portrait mode, our website shows that we have curated a new app for them on the play store app and even after switching to landscape mode, on a mobile device, it still shows that we have curated a new app for them on the play store app. I don't think there's any issue but I believe you are a lazy ****. I would request you to not be a **** and resolve the issues assigned to you or attach a screenshot of the orientation issue.
Thanks :)

Edit : removed a few words.

**Comment by abhishak3** [comment]
https://user-images.githubusercontent.com/77143429/169074361-bab599f8-2584-4d44-8ea9-b1b63eea9240.mp4

I think you need to see this !

**Comment by the-iter8** [comment]
sorry

**Comment by the-iter8** [comment]
Fixed. Thanks.

**Comment by abhishak3** [comment]
GG
