### ISSUE TITLE
Add functionality to the "learn more", "edit" and "delete" button(s).

### ISSUE THREAD

**Issue by the-iter8** [the-iter8/Noted#3]
We could modify the learn more button to something else, also we need to work on the edit and delete button and make it functional.

**Comment by the-iter8** [comment]
It's partially solved, we'll discuss what do we have to do with the learn more button.

**Comment by abhishak3** [comment]
Absolutely

**Comment by the-iter8** [comment]
Currently, I believe that we've resolved the issue partially, (about 67%) so I will close this issue and will open another issue for the learn more button.
